export default {

    '서울' : 'seoul',
    '시즈오카' : 'shizuoka',
    '홍콩' : 'hongkong',
    '삿포로' : 'sapporo',
    '오사카' : 'osaka',
    '후쿠오카' : 'fukuoka',
    '다낭' : 'Da Nang',
    '타이페이' : 'Taipei',
    '호치민' : 'ho chi minh',
    '런던' : 'London',
    '시드니' : 'Sydney',
    '멜버른' : 'Melbourne',
    '마드리드' : 'Madrid',
    '로마' : 'Rome',
    '괌' : 'Guam',
    '사이판' : 'Saipan ',
    '파리' : 'paris',
    '하노이' : 'Hanoi',
    '강원도' : 'Gangwon-do',
    '나트랑' : 'Nha Trang',
    '로스앤젤레스' : 'Los Angeles',
    '뉴욕' :'new york' ,
    '뮌헨' : 'Munich',
    '밴쿠버' : 'Vancouver',
    '달랏' : 'Da Lat',
    '방콕' : 'Bangkok',
    '푸꾸옥' : 'Phuket',
    '토론토' : 'Toronto',
    '베를린' : 'Berlin',
    '제주도' : 'jeju',
    '바르셀로나' : 'Barcelona',
    '칸쿤' : 'cancun',

  };
  