const weatherData = {

    200: { icon : '11d', description : '비를 동반한 천둥구름'},
    202: { icon : '11d', description : '폭우를 동반한 천둥구름'},
    201: { icon : '11d', description : '가벼운 비를 동반한 천둥구름'},
    210: { icon : '11d', description : '약한 천둥구름'},
    211: { icon : '11d', description : '천둥구름'},
    212: { icon : '11d', description : '강한 천둥구름'},
    221: { icon : '11d', description : '불규칙적 천둥구름'},
    230: { icon : '11d', description : '약한 연무를 동반한 천둥구름'},
    231: { icon : '11d', description : '연무를 동반한 천둥구름'},
    232: { icon : '11d', description : '강한 안개비를 동반한 천둥구름'},
    300: { icon : '09d', description : '가벼운 안개비'},
    301: { icon : '09d', description : '안개비'},
    302: { icon : '09d', description : '강한 안개비'},
    310: { icon : '09d', description : '가벼운 적은비'},
    311: { icon : '09d', description : '적은비'},
    312: { icon : '09d', description : '강한 적은비'},
    313: { icon : '09d', description : '소나기와 안개비'},
    314: { icon : '09d', description : '강한 소나기와 안개비'},
    321: { icon : '09d', description : '소나기'},
    500: { icon : '10d', description : '약한 비'},
    501: { icon : '10d', description : '중간 비'},
    502: { icon : '10d', description : '강한 비'},
    503: { icon : '10d', description : '매우 강한 비'},
    504: { icon : '10d', description : '극심한 비'},
    511: { icon : '13d', description : '우박'},
    520: { icon : '09d', description : '약한 소나기'},
    521: { icon : '09d', description : '소나기'},
    522: { icon : '09d', description : '강한 소나기'},
    531: { icon : '09d', description : '불규칙적 소나기'},
    600: { icon : '13d', description : '가벼운 눈'},
    601: { icon : '13d', description : '눈'},
    602: { icon : '13d', description : '강한 눈'},
    611: { icon : '13d', description : '진눈깨비'},
    612: { icon : '13d', description : '소나기 진눈깨비'},
    615: { icon : '13d', description : '약한 비와 눈'},
    616: { icon : '13d', description : '비와 눈'},
    620: { icon : '13d', description : '약한 소나기 눈'},
    621: { icon : '13d', description : '소나기 눈'},
    622: { icon : '13d', description : '강한 소나기 눈'},
    701: { icon : '50d', description : '박무'},
    711: { icon : '50d', description : '연기'},
    721: { icon : '50d', description : '연무'},
    731: { icon : '50d', description : '모래먼지'},
    741: { icon : '50d', description : '안개'},
    751: { icon : '50d', description : '모래'},
    761: { icon : '50d', description : '먼지'},
    762: { icon : '50d', description : '화산재'},
    771: { icon : '50d', description : '돌풍'},
    781: { icon : '50d', description : '토네이도'},
    800: { icon : '01d', description : '구름 한점 없는 맑은 하늘'},
    801: { icon : '02d', description : '약간의 구름이 낀 하늘'},
    802: { icon : '03d', description : '드문드문 구름이 낀 하늘'},
    803: { icon : '04d', description : '구름이 거의 없는 하늘'},
    804: { icon : '04d', description : '구름으로 뒤덮인 흐린 하늘'},
    900: { icon : '50d', description : '토네이도'},
    901: { icon : '50d', description : '태풍'},
    902: { icon : '50d', description : '허리케인'},
    903: { icon : '50d', description : '한랭'},
    904: { icon : '50d', description : '고온'},
    905: { icon : '50d', description : '바람부는'}, 
    906: { icon : '13d', description : '우박'},
    951: { icon : '01d', description : '바람이 거의 없는'},
    952: { icon : '02d', description : '약한 바람'},
    953: { icon : '03d', description : '부드러운 바람'},
    954: { icon : '04d', description : '중간 세기 바람'},
    955: { icon : '04d', description : '신선한 바람'},
    956: { icon : '50d', description : '센 바람'},
    957: { icon : '50d', description : '돌풍에 가까운 센 바람'},
    958: { icon : '50d', description : '돌풍'},
    959: { icon : '50d', description : '심각한 돌풍'},
    960: { icon : '50d', description : '폭풍'},
    961: { icon : '50d', description : '강한 폭풍'},
    962: { icon : '50d', description : '허리케인'},
    
};

export default weatherData;